const crypto = require('crypto');

function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(password, salt, 64).toString('hex');
  return `${salt}:${hash}`;
}

const now = new Date().toISOString();

const users = [
  {
    id: 'a0000000-0000-0000-0000-000000000001',
    name: 'Admin User',
    email: 'admin@crimewatch.gov',
    phone: '+1-555-0100',
    password: hashPassword('Admin@123'),
    role: 'admin',
    status: 'active',
    city: 'New York',
    state: 'NY',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000002',
    name: 'Police Commissioner',
    email: 'commissioner@crimewatch.gov',
    phone: '+1-555-0101',
    password: hashPassword('Police@123'),
    role: 'police',
    status: 'active',
    city: 'New York',
    state: 'NY',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000003',
    name: 'Officer Johnson',
    email: 'johnson@crimewatch.gov',
    phone: '+1-555-0102',
    password: hashPassword('Police@123'),
    role: 'police',
    status: 'active',
    city: 'New York',
    state: 'NY',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000004',
    name: 'Officer Williams',
    email: 'williams@crimewatch.gov',
    phone: '+1-555-0103',
    password: hashPassword('Police@123'),
    role: 'police',
    status: 'active',
    city: 'Los Angeles',
    state: 'CA',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000005',
    name: 'Officer Brown',
    email: 'brown@crimewatch.gov',
    phone: '+1-555-0104',
    password: hashPassword('Police@123'),
    role: 'police',
    status: 'active',
    city: 'Chicago',
    state: 'IL',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000006',
    name: 'John Citizen',
    email: 'john.citizen@email.com',
    phone: '+1-555-0105',
    password: hashPassword('Citizen@123'),
    role: 'citizen',
    status: 'active',
    city: 'New York',
    state: 'NY',
    address: '123 Main St, Manhattan, NY',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000007',
    name: 'Jane Citizen',
    email: 'jane.citizen@email.com',
    phone: '+1-555-0106',
    password: hashPassword('Citizen@123'),
    role: 'citizen',
    status: 'active',
    city: 'Los Angeles',
    state: 'CA',
    address: '456 Sunset Blvd, LA, CA',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000008',
    name: 'Bob Citizen',
    email: 'bob.citizen@email.com',
    phone: '+1-555-0107',
    password: hashPassword('Citizen@123'),
    role: 'citizen',
    status: 'active',
    city: 'Chicago',
    state: 'IL',
    address: '789 Michigan Ave, Chicago, IL',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000009',
    name: 'Suspended User',
    email: 'suspended@email.com',
    phone: '+1-555-0108',
    password: hashPassword('Suspended@123'),
    role: 'citizen',
    status: 'suspended',
    city: 'New York',
    state: 'NY',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'a0000000-0000-0000-0000-000000000010',
    name: 'Inactive User',
    email: 'inactive@email.com',
    phone: '+1-555-0109',
    password: hashPassword('Inactive@123'),
    role: 'citizen',
    status: 'inactive',
    city: 'Los Angeles',
    state: 'CA',
    created_at: now,
    updated_at: now,
    created_by: 'system',
    updated_by: 'system',
  },
];

async function seed(knex) {
  const exists = await knex.schema.hasTable('users');
  if (!exists) return;
  const count = await knex('users').count('* as total').first();
  if (parseInt(count?.total || 0, 10) > 0) return;
  await knex.batchInsert('users', users, 50);
}

module.exports = { seed, name: 'users', dependencies: ['users'] };
